### ISSUE TITLE
hr/motd for welcome messages

### ISSUE THREAD

**Issue by XHerna** [morko/hhm-sala-plugins#6]
Often people want to write messages like "Welcome @Herna" as welcome message. With the motd-plugin it isnt possible to adress the joined player individually though. And those should be different from those that get repeated in intervals then, I guess.

**Comment by morko** [comment]
Ok. I will implement some template string like "Welcome {player}" to add this and a separate message for the player joining and what is displayed periodically.

**Comment by morko** [comment]
Implemented in development branch. Will merge to master later.
